### ISSUE TITLE
display link in 2 lines only not more

### ISSUE THREAD

**Issue by progzidan2018** [griddb/nodejs_client#3]
hey guys, i want to make my linke show only on 2 line only
![screenshot_2018-09-05 with prophet](https://user-images.githubusercontent.com/42411018/45084998-e92d2880-b0ff-11e8-8bec-b1d1923ca6f1.png)
and i want to make it like 
![screenshot_2018-09-05 with prophet 1](https://user-images.githubusercontent.com/42411018/45085093-21346b80-b100-11e8-9c95-cfdee7c2033a.png)
and the code of css is [
.list_item_link {
    color: Black;
    font-size: 13px;
    line-height: 1.7;
    }
]
but i want to display only 2 lines no more.
thanks in advanced!!!!

**Comment by progzidan2018** [comment]
sorry i am new to github issues

**Comment by knonomura** [comment]
Thank you for your access into our repository.

I will close your issue(pull request) as it is not related to this repository.
If any issue and question related to GridDB server or client, please open a new issue.
